Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,14 +68,14 @@ jobs:
             local target_json="$1"
             local default_project_name=$(echo "$target_json" | jq -r '.target.url | rtrimstr("https://") | rtrimstr("http://")')
             default_project_name="${default_project_name//\//-}"
-            # echo "$target_json"
-            # response=$(import_target "$target_json")
-            # status_code=$(echo "$response" | jq -r '.statusCode')
+            echo "$target_json"
+            response=$(import_target "$target_json")
+            status_code=$(echo "$response" | jq -r '.statusCode')
 
-            # if [[ "$status_code" -ne 200 ]]; then
-            #   echo "Error importing target: $response"
-            #   exit 1
-            # fi
+            if [[ "$status_code" -ne 200 ]]; then
+              echo "Error importing target: $response"
+              exit 1
+            fi
 
             sleep 5 # Adjust sleep time as needed
 
